---
title: "Pre processing data with Buccaneer"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pre-processing-data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  eval = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval=FALSE}
library(Buccaneer)
```

:::callout-note
This page is under construction
:::

# General cleaning and processing



# Processing and flagging data with `Buccaneer`

    
```{r, echo=FALSE,eval=FALSE}
df_occ_faurby <- 
  clean_occ_fossil(df.occ.fossil = df.faurby4, 
                 method.ages = "midpoint",
                 thresh.age.range = 5, 
                 species = "Genus",
                 Max.age = "Maximum_Age",
                 Min.age = "Minimum_Age", 
                 site = "site",
                 lat = "Latitude",
                 lng = "Longitude",
                 remove.sub.species = TRUE, 
                 comp.TS.TE = TRUE, 
                 group = "Suborder")
```


```{r,echo=FALSE,eval=FALSE}
df_occ_faurby <- 
  df_occ_faurby |> 
  filter(species != "Delete")

# filtering TS and TE per species

df_TS_TE_faurby <- 
  df_occ_faurby |> 
  dplyr::distinct(species, .keep_all = T)

# joining TS and TE with body mass

df_TS_TE_mass <- 
  df_body_mass |> 
  left_join(df_TS_TE_faurby, by = c(Genus = "species")) |> 
  rename(species = "Genus") |> 
  filter(!is.na(TS) & !is.na(TE)) |> 
  filter(!is.na(site))

# creating time intervals (bins)

bins <- seq(from = max(df_occ_faurby$Max.age), to = min(df_occ_faurby$Min.age), by = -5)

```

