#' Calculate Species Co-occurrence Matrices Based on Site Overlap Across Time Slices
#'
#' This auxiliary function computes species-by-species co-occurrence matrices for
#' each time slice based on shared site occupancy. Two species are considered to
#' co-occur if they are found at the same site during the same time slice. The
#' resulting matrices quantify how many sites each pair of species shares, which
#' can be used to calculate trait distances among co-occurring species.
#'
#' @param spp_slice A named list where each element contains a character vector
#'     of species names present in a given time slice. Names of list elements
#'     should be time slice identifiers (typically numeric values). Usually
#'     generated by \code{calc_spp_slice()}.
#' @param df.occ A data frame containing fossil occurrence records with at least
#'     four columns: species names, minimum age, maximum age, and site location ID.
#'     Each row represents a single occurrence record at a specific site. Column
#'     names should match the parameters below.
#' @param species Character. The name of the column in \code{df.occ} containing
#'     species identifiers. Default is "species".
#' @param Max.age Character. The name of the column in \code{df.occ} containing
#'     the maximum (oldest) age estimate for each occurrence record. Default is "Max.age".
#' @param Min.age Character. The name of the column in \code{df.occ} containing
#'     the minimum (youngest) age estimate for each occurrence record. Default is "Min.age".
#' @param site Character. The name of the column in \code{df.occ} containing
#'     site location identifiers. Default is "site".
#'
#' @return A list with length equal to the number of time slices in \code{spp_slice}.
#'     Each element is a square matrix (species × species) where:
#'     \itemize{
#'       \item Row and column names are species names
#'       \item Diagonal elements represent the number of sites where each species occurs
#'       \item Off-diagonal elements represent the number of shared sites between
#'             pairs of species
#'       \item Values of 0 indicate no site overlap between species pairs
#'     }
#'
#' @details
#' The function performs the following steps for each time slice:
#' \enumerate{
#'   \item Filters \code{df.occ} to include only species present in the time slice
#'   \item Further filters occurrences where the age range overlaps with the time slice
#'         (Max.age >= time slice AND Min.age <= time slice)
#'   \item Removes duplicate species records within sites
#'   \item Creates a site-by-species presence/absence matrix
#'   \item Computes the cross-product (t(matrix) \%*\% matrix) to generate a
#'         species-by-species co-occurrence matrix
#' }
#'
#' The resulting co-occurrence matrix quantifies spatial overlap:
#' \itemize{
#'   \item Diagonal values = total number of sites occupied by each species
#'   \item Off-diagonal values = number of sites shared by species pairs
#'   \item This differs from simple presence/absence (0/1) co-occurrence
#' }
#'
#' This function is typically used internally by \code{IndivSpec_site_distance()}
#' and related functions to determine which species co-occur at sites before
#' calculating trait-based community metrics.
#'
#' @import dplyr
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Create example species composition per time slice
#' spp_slice <- list(
#'   "100" = c("sp1", "sp2", "sp3"),
#'   "90" = c("sp1", "sp2", "sp4"),
#'   "80" = c("sp2", "sp3", "sp4")
#' )
#'
#' # Create example occurrence data
#' df_occurrences <- data.frame(
#'   species = c("sp1", "sp1", "sp1", "sp2", "sp2", "sp3", "sp3", "sp4"),
#'   Max.age = c(100, 100, 95, 100, 90, 95, 95, 85),
#'   Min.age = c(90, 90, 85, 80, 75, 80, 85, 70),
#'   site = c("site1", "site2", "site3", "site1", "site2", "site1", "site3", "site2")
#' )
#'
#' # Generate co-occurrence matrices for each time slice
#' cooccur_matrices <- comp_site_cooccurr(
#'   spp_slice = spp_slice,
#'   df.occ = df_occurrences
#' )
#'
#' # View first time slice co-occurrence matrix
#' cooccur_matrices[[1]]
#'
#' # Convert to binary co-occurrence (present/absent)
#' binary_cooccur <- ifelse(cooccur_matrices[[1]] >= 1, 1, 0)
#'
#' # Calculate co-occurrence frequency for a species pair
#' shared_sites_sp1_sp2 <- cooccur_matrices[[1]]["sp1", "sp2"]
#'
#' }
comp_site_cooccurr <-
  function(spp_slice,
           df.occ,
           species = "species",
           Max.age = "Max.age",
           Min.age = "Min.age",
           site = "site"){

    #df_occ <-
    #  df.occ[, c(species, Max.age, Min.age, site)]


    # data frame with species per slice
    list_site_interval <-
      lapply(1:length(spp_slice), function(x){
        names_slices <- names(spp_slice)[[x]]
        names_species <- spp_slice[[x]]
        filtered_df <-
          df.occ |> filter(species %in% names_species)

        filtered_df_site <-
          filtered_df |>
          filter(Max.age >= as.numeric(names_slices) & Min.age <= as.numeric(names_slices))

        spp_coex_site <-
          filtered_df_site |>
          dplyr::distinct(species, .keep_all = TRUE) |>
          dplyr::select(species, Max.age, Min.age)

        filtered_df_site2 <-
          filtered_df_site |>
          group_by(site) |>
          dplyr::distinct(species, .keep_all = T) |>
          add_count(site, name = "species.per.site") |>
          dplyr::select(species, site, Max.age, Min.age, species.per.site)

        return(filtered_df_site2)
      })

    # calculate species cooccurrence matrix for each timeslice besed on site cooccurrence
    list_matrix_cooccur_site <-
      lapply(list_site_interval, function(x){

        # Step 1: Remove duplicates to avoid counting same species twice in a site
        df_unique <-
          x |>
          dplyr::distinct(site, species)

        # Step 2: Create a presence/absence matrix (sites x species)
        site_species_matrix <-
          df_unique  |>
          mutate(present = 1) |>
          tidyr::pivot_wider(names_from = species, values_from = present, values_fill = 0)

        # Step 3: Convert to a matrix and compute cross-product
        mat <- as.matrix(site_species_matrix[,-1])  # remove site column
        cooccur_matrix_sites <- t(mat) %*% mat  # species-by-species co-occurrence
        cooccur_matrix_sites
      })

    return(list_matrix_cooccur_site)
  }

