#' Calculate Species Co-occurrence Matrices Based on Time Slice Overlap
#'
#' This auxiliary function computes species-by-species co-occurrence matrices for
#' each time slice based on shared site occupancy. Two species are considered to
#' co-occur if they are found at the same site during the same time slice. The
#' resulting matrices quantify how many sites each pair of species shares, which
#' can be used to calculate trait distances among co-occurring species.
#'
#' @param spp_slice A named list where each element contains a character vector
#'     of species names present in a given time slice. Names of list elements
#'     should be time slice identifiers (typically numeric values). Usually
#'     generated by \code{calc_spp_slice()}.
#' @param df.occ A data frame containing fossil occurrence records with at least
#'     four columns: species names, minimum age, maximum age, and site location ID.
#'     Each row represents a single occurrence record at a specific site. Column
#'     names should match the parameters below.
#' @param species Character. The name of the column in \code{df.occ} containing
#'     species identifiers. Default is "species".
#' @param Max.age Character. The name of the column in \code{df.occ} containing
#'     the maximum (oldest) age estimate for each occurrence record. Default is "Max.age".
#' @param Min.age Character. The name of the column in \code{df.occ} containing
#'     the minimum (youngest) age estimate for each occurrence record. Default is "Min.age".
#'
#' @return A list with length equal to the number of time slices in \code{spp_slice}.
#'     Each element is a square matrix (species × species) where:
#'     \itemize{
#'       \item Row and column names are species names
#'       \item Diagonal elements represent the number of sites where each species occurs
#'       \item Off-diagonal elements represent the number of shared sites between
#'             pairs of species
#'       \item Values of 0 indicate no site overlap between species pairs
#'     }
#'
comp_slice_occ_cooccurr <-
  function(spp_slice,
           df.occ,
           species = "species",
           Max.age = "Max.age",
           Min.age = "Min.age"){

    #df_occ <-
    #  df.occ[, c(species, Max.age, Min.age, site)]


    # data frame with species per slice
    list_site_interval <-
      lapply(1:length(spp_slice), function(x){
        names_slices <- names(spp_slice)[[x]]
        names_species <- spp_slice[[x]]
        filtered_df <-
          df.occ |> filter(species %in% names_species)

        filtered_df_site <-
          filtered_df |>
          filter(Max.age >= as.numeric(names_slices) & Min.age <= as.numeric(names_slices))

        return(filtered_df_site)
      })

    # data frame with occurrence records per time slice
    return(list_site_interval)
  }

